// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXVRLZ-nv5kc0OkgayVjPvv3FRW5yBFCo',
    appId: '1:191792960483:web:f5e8e8bd26cf8037b946d6',
    messagingSenderId: '191792960483',
    projectId: 'fir-tutorial-36108',
    authDomain: 'fir-tutorial-36108.firebaseapp.com',
    storageBucket: 'fir-tutorial-36108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoeVSl-kBIld8tB1AF8gUPTQxJhTHKo_U',
    appId: '1:191792960483:android:22b03c58fde8599bb946d6',
    messagingSenderId: '191792960483',
    projectId: 'fir-tutorial-36108',
    storageBucket: 'fir-tutorial-36108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2UEF_EMgrLkDkOGo4nusYBgjdMowXqAs',
    appId: '1:191792960483:ios:2260c9f14b979366b946d6',
    messagingSenderId: '191792960483',
    projectId: 'fir-tutorial-36108',
    storageBucket: 'fir-tutorial-36108.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2UEF_EMgrLkDkOGo4nusYBgjdMowXqAs',
    appId: '1:191792960483:ios:2260c9f14b979366b946d6',
    messagingSenderId: '191792960483',
    projectId: 'fir-tutorial-36108',
    storageBucket: 'fir-tutorial-36108.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
